name: check feed

on:
  schedule:
    - cron: "*/15 * * * *"
  push: {branches: main}
  workflow_dispatch:

jobs:
  check-feed:
    runs-on: ubuntu-latest
    name: check, trigger & commit
    steps:
      - uses: actions/checkout@v3
      - name: "check rss"
        id: "check"
        uses: tamanishi/check-rebuild-feed@v0.1
      - name: "update json"
        if: steps.check.outputs.result == 'updated'
        run: |
          curl -v -H "Authorization: token ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/tamanishi/rebuild_feed_to_json_go/dispatches" -d '{"event_type": "update-episodes"}'
      - name: "commit rss"
        if: steps.check.outputs.result == 'updated'
        run: |
          git add ./rss.xml
          git config user.name "Masayuki Sunahara"
          git config user.email tamanishi@gmail.com
          git commit -m "update episodes"
          git push origin main
