name: check feed

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check-feed:
    runs-on: ubuntu-latest
    name: check, trigger & commit
    steps:
      - uses: actions/checkout@v3
      - name: "check rss"
        id: "check"
        uses: tamanishi/check-rebuild-feed@v0.1
      - name: "update json"
        if: steps.check.outputs.result == 'updated'
        run: |
          curl -v -H "Authorization: token ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/tamanishi/rebuild_feed_to_json_go/dispatches" -d '{"event_type": "update-episodes"}'
      - name: "update d1"
        if: steps.check.outputs.result == 'updated'
        run: |
          curl -v https://rebuild-shownotes.tamanishi.workers.dev
      - name: "commit rss"
        if: steps.check.outputs.result == 'updated'
        run: |
          git add ./rss.xml
          git config user.name "Masayuki Sunahara"
          git config user.email tamanishi@gmail.com
          git commit -m "update episodes"
          git push origin main
      - name: notify success
        if: ${{ success() && steps.check.outputs.result == 'updated' }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"value1": "${{ github.repository }}", "value2": "succeeded"}' https://maker.ifttt.com/trigger/update_rebuild_json/with/key/${{ secrets.IFTTT_WEB_HOOK_KEY }}
      - name: notify fail
        if: ${{ failure() }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"value1": "${{ github.repository }}", "value2": "failed"}' https://maker.ifttt.com/trigger/update_rebuild_json/with/key/${{ secrets.IFTTT_WEB_HOOK_KEY }}
